name: teammate
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Управление состоянием
  equatable: ^2.0.5
  


  # Шрифты
  google_fonts: ^5.1.0

  # Форматирование дат и перевод
  flutter_localizations:
    sdk: flutter         
  localization: ^2.1.0
  intl: ^0.18.0

  dropdown_search: ^5.0.5
  cupertino_stepper: ^0.2.1
  dropdown_button2: ^1.9.3
  pinput: ^2.2.30

  firebase_core: ^2.24.0
  firebase_auth: ^4.2.8
  firebase_storage: ^11.5.3
  cloud_firestore: ^4.13.3
  firebase_messaging: ^14.6.2
  
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0

  fluttertoast: ^8.2.1

  mask_text_input_formatter: ^2.4.0

  device_info_plus: ^9.0.1

  flutter_local_notifications: ^14.1.0


  translit: ^2.0.1

  permission_handler: ^10.3.0
  share_plus: ^7.0.2
  collection: ^1.17.2
  
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1


  
  

  
  
    
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

  very_good_analysis: ^4.0.0
  # Автогенерация картинок
  spider: ^4.2.2
  freezed: ^2.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/teammate-logo.png"
  min_sdk_android: 21 
  remove_alpha_ios: true
  

flutter:
  assets:
    - assets/
    - assets/cities/
  uses-material-design: true

 