name: teammate
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Управление состоянием
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  
  # Навигация
  # go_router: ^5.0.5
  get_it: ^7.2.0

  # Шрифты
  google_fonts: ^4.0.3

  # Форматирование дат и перевод
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter         
  dropdown_search: ^5.0.5
  cupertino_stepper: ^0.2.1
  dropdown_button2: ^1.9.3
  pinput: ^2.2.30
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.8
  firebase_storage: ^11.0.13
  cloud_firestore: ^4.4.2
  shared_preferences: ^2.0.17
  provider: ^6.0.5
  fluttertoast: ^8.2.1
  flutter_secure_storage: ^8.0.0
  
  
    
dev_dependencies:
  flutter_lints: ^2.0.0
  very_good_analysis: ^4.0.0+1
  # Автогенерация картинок
  spider: ^4.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true

 